# Generated by Django 4.2.4 on 2023-10-29 16:58

import borrowed_book_list.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowed_book_list', '0003_alter_peminjaman_tanggal_pengembalian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pengembalian',
            field=models.DateField(default=borrowed_book_list.models.in_seven_days, verbose_name=borrowed_book_list.models.in_seven_days),
        ),
    ]
