# Generated by Django 4.2.4 on 2023-10-26 08:20

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "daftar_peminjam.json")

class Migration(migrations.Migration):

    dependencies = [
        ('daftar_peminjam', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]