# Generated by Django 4.2.4 on 2023-10-27 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daftar_peminjam', '0003_auto_20231026_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
