# Generated by Django 4.2.4 on 2023-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_peminjam', '0004_alter_peminjam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjam',
            name='pengembalian_paling_awal',
        ),
        migrations.AlterField(
            model_name='peminjam',
            name='book_list',
            field=models.ManyToManyField(blank=True, null=True, to='daftar_peminjam.peminjaman'),
        ),
    ]
