# Generated by Django 4.2.4 on 2023-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_keranjang_book_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peminjam",
            name="book_list",
        ),
        migrations.AddField(
            model_name="peminjam",
            name="peminjaman_list",
            field=models.ManyToManyField(null=True, to="home.peminjaman"),
        ),
        migrations.AlterField(
            model_name="keranjang",
            name="book_list",
            field=models.ManyToManyField(blank=True, null=True, to="home.book"),
        ),
        migrations.AlterField(
            model_name="peminjaman",
            name="tanggal_pengembalian",
            field=models.DateField(null=True),
        ),
    ]
