# Generated by Django 4.2.6 on 2023-10-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_isbn'),
        ('home', '0003_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keranjang',
            name='book_list',
            field=models.ManyToManyField(to='book.book'),
        ),
        migrations.AlterField(
            model_name='peminjam',
            name='book_list',
            field=models.ManyToManyField(to='book.book'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
