# Generated by Django 4.2.4 on 2023-10-28 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_peminjam_book_list_peminjam_peminjaman_list_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
