# Generated by Django 4.2.4 on 2023-10-28 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_keranjang_book_list_alter_peminjam_book_list_and_more"),
        ("home", "0004_delete_review"),
    ]

    operations = []
