# Generated by Django 4.2.4 on 2023-10-28 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_merge_20231028_2240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keranjang",
            name="book_list",
            field=models.ManyToManyField(to="home.book"),
        ),
        migrations.AlterField(
            model_name="peminjam",
            name="peminjaman_list",
            field=models.ManyToManyField(to="home.peminjaman"),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("rate", models.IntegerField()),
                ("review_date", models.DateField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
