# Generated by Django 4.2.4 on 2023-10-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.IntegerField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("author", models.TextField(blank=True, null=True)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("publisher", models.TextField(blank=True, null=True)),
                ("image_s", models.TextField(blank=True, null=True)),
                ("image_m", models.TextField(blank=True, null=True)),
                ("image_l", models.TextField(blank=True, null=True)),
                ("stock", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
