# Generated by Django 4.2.4 on 2023-10-22 02:21

from django.db import migrations
from django.core.management import call_command

class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "book.json")

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]