# Generated by Django 4.2.4 on 2023-10-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_auto_20231022_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.TextField(blank=True, null=True),
        ),
    ]
