# Generated by Django 4.2.4 on 2023-10-28 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_book_isbn"),
    ]

    operations = []
